### ISSUE TITLE
Error to running script Collab

### ISSUE THREAD

**Issue by gjpsiqueira** [zerausolrac/PyCollab#9]
Python version testing: 3.9
Python version testing: 3.8
Python version testing: 3.7

## Steps To Reproduce
1.  pip install -r requerimientos.txt
1. edit files learn_courses.txt
1. python3 Collab.py -f learn_courses.txt

## The current behavior

```
Course Recordings from 2020-09-22T02:30:42Z
[auth:setToken()] ERROR: <Response [400]>
[auth:setToken()] ERROR: <Response [400]>
Traceback (most recent call last):
  File "/usr/src/app/controladores/AuthControlador.py", line 59, in getToken
    token = self.cache['token']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Collab.py", line 21, in <module>
    course_uuids.append(webService.getUUID(curso))
  File "/usr/src/app/webService.py", line 77, in getUUID
    token = self.getToken()
  File "/usr/src/app/webService.py", line 36, in getToken
    return(self.sesion.getToken())
  File "/usr/src/app/controladores/AuthControlador.py", line 69, in getToken
    return self.cache['token']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by zerausolrac** [comment]
are this steps reviewed?
https://github.com/zerausolrac/PyCollab#note-backboard-credentials--integration-on-learn
https://github.com/zerausolrac/PyCollab/blob/master/LearnPyCollab.pdf

**Comment by gjpsiqueira** [comment]
Hi, @zerausolrac 

It worked! However, not can downloaded, appears the following message:

```
Course Recordings from 2020-10-06T12:50:01Z
No downloading was executed
Report: recordingReport_403.csv created!
```

Thank you!

**Comment by zerausolrac** [comment]
Hi @gjpsiqueira, based on the report created, seems like that those recordings are private (public_access off), so the owner of the recording must allow it, in order to get the recording .

check: https://help.blackboard.com/Collaborate/Ultra/Administrator/Release_Notes#:~:text=The%20new%20whiteboard%20was%20released,broader%20audience%20September%2010,%202020 on Secure recording links section.

Note: Switch it to public, anyone can view playback the recording with the URL.

Thank you!

**Comment by gjpsiqueira** [comment]
Hi @zerausolrac,
Thank you for answering all questions.
